## Used to define some reused variables
defaults:
  architectures: &ARCH
   - amd64
  components: &COMP
   - main
#   - non-free

## List of archives to process
archives:
   ## A name given to the archive
  debian:
    ## Name of the tracefile to use for determine how up to date
    ## the archive is.
    tracefile: package-server
    ## Where the archive is placed on the file system
    base-dir: /var/www/public/stretch
    ## Architectures to process
    architectures: *ARCH
    ## Which components to process
    components: *COMP
    ## Which suites/distributions to process
    distributions:
     - current
#     - current-release140

storage:
## Path to the log files
  log-dir: /var/www/lintian-reports/logs
## Path to directory hold temporary data used by lintian.
## Used as TMPDIR for lintian and will also hold temporary labs
## - Can be /var/tmp or /tmp as long as they have space enough
## - Can be cleaned automatically.  Either on boot or via a
##   "delete anything older than X days"-mechanism
  scratch-space: /var/www/lintian-reports/scratch
## Path to a directory to hold cached data like which packages
## have been processed.
## - Can be in /var/cache
## - Can be deleted to reset / restart processing from scratch
  state-cache: /var/www/lintian-reports/harness-state
## Where to store latest completed report / static website
  reports-dir: /var/www/lintian-reports/www
## Directory to use for compiling new reports
## FIXME: This should just be a tmpdir
  reports-work-dir: /var/www/lintian-reports/www.tmp
## Where to store collected data / historical data (used for
## generating graphs etc.)
  historical-data-dir: /var/www/lintian-reports/history

lintian:
## Extra options to pass to lintian (not all options can be
## passed via this.  E.g. --cfg is ignored).
#  extra-options: ['--jobs', '2']
  extra-options: ['--suppress-tags-from-file', 'suppressed-tags.txt']

## All of these variables will be available for templates to consume
## via "$config_vars{VAR}"
template-variables:
  LINTIAN_SOURCE: https://github.com/sdelafond/lintian.git

## Source packages to not process
#blacklist:
# - gcc-8-cross-ports # #890873
