version: '2'
services:
  lintian-reports:
    image: untangleinc/ngfw:lintian
    volumes:
      - /var/www/public/stretch:/var/www/public/stretch
      - /var/www/lintian-reports:/var/www/lintian-reports
    command: -i --to-stdout
